name: 'ChristoSays!'
favicon: null
layout_spectrum: 0.9389184289611876
typography_spectrum: 0.29028
title: 'Barista by day. Tech enthusiast by night '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#433a3f'
    - '#07060c'
    - '#787e8a'
    - '#b1aba9'
    - '#f7f1f1'
  brandStrength: 0.875
  lightness: 0.21348761557601392
  saturation: 0.125
  rhythmicContrast: 0.9991065389476717
purpose: []
